services:
  maintenance:
    image: gcr.io/swallo/maintsrv:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintenance.rule=Host(`maintenance.local`)"
      - "traefik.http.routers.maintenance.entrypoints=websecure"
      - "traefik.http.routers.maintenance.tls=true"
      - "traefik.http.routers.maintenance.tls.certresolver=letsencrypt"
    networks:
      - default
      - traefik_global
    environment:
      # Optionally override the static directory
      STATIC_DIR: /static

networks:
  traefik_global:
    external: true
